sudo: required 
language: node_js
node_js:
    - 16  
services: 
    - docker
before_install: 
    - docker build -t destinywarriorshen/sample-app Dockerfile.dev .
script:     
    - docker run -e CI=true destinywarriorshen/sample-app npm run test -- --coverage --watchAll=false